script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: XFpDKthOSyZOStk2Riyon1SW7DsS3UWE7wfXP4ihnazJtERuI340ipW8jRBswpqBtKGYF8lA8QNGO0/2PwOT3yG5QUeQtKt8qlno0mSj+piKP7jBnthgpZN2KT605fsOGqIc54c+i4BSzSeeWMBTfY3tulj5jq3meI55I22235A=
  app:
    develop: anbu-core-func01
