script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: dbSylWTDz6sRMMbu6bj+xLACCyD77fI/OBu9DMxScab8+1sfD8u1OsxMY7JSw2smEcHitggOinJm4B3p5R5KEAfnVXw4/0gA/PlyAqpbTduMKqahcDT+tdAPfx2kLuKqglgiXHv5oJh2gODXDHCloKSv9NFo6Kdytxm6qWrUycE=
  app: anbu-core-func01
  on:
    repo: thyms/anbu-core
    branch: develop
