script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: UqcCEe1sP8PRXARTkFaiGg/ig3UueTAgINtCknpoSKnJLHJgvs14hxgpwL6G+8Bk/nBy4fTMQ0QCoIOf/kITdkPC7Aa51JLvrqwcpc3yR5zF7jYv1wYfczbipRR7UHSg1CJc2nCmZCX9LigRFpzqx3O7tnjc+0JCaM7gulDVeR8=
  app:
    develop: anbu-core-func01
